# coding: utf-8

"""
    College Football Risk API

    Companion API for College Football Risk  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Contact: admin@collegefootballdata.com
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest
import datetime

import college_football_risk
from college_football_risk.models.territory_turn_teams import TerritoryTurnTeams  # noqa: E501
from college_football_risk.rest import ApiException

class TestTerritoryTurnTeams(unittest.TestCase):
    """TerritoryTurnTeams unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional):
        """Test TerritoryTurnTeams
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # model = college_football_risk.models.territory_turn_teams.TerritoryTurnTeams()  # noqa: E501
        if include_optional :
            return TerritoryTurnTeams(
                team = '0', 
                color = '0', 
                secondary_color = '0', 
                players = 56, 
                power = 56, 
                chance = 1.337, 
                breakdown = college_football_risk.models.team_history_star_breakdown.TeamHistory_starBreakdown(
                    ones = 56, 
                    twos = 56, 
                    threes = 56, 
                    fours = 56, 
                    fives = 56, )
            )
        else :
            return TerritoryTurnTeams(
        )

    def testTerritoryTurnTeams(self):
        """Test TerritoryTurnTeams"""
        inst_req_only = self.make_instance(include_optional=False)
        inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == '__main__':
    unittest.main()
