# coding: utf-8

"""
    College Football Risk API

    Companion API for College Football Risk  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Contact: admin@collegefootballdata.com
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest

import college_football_risk
from college_football_risk.api.teams_api import TeamsApi  # noqa: E501
from college_football_risk.rest import ApiException


class TestTeamsApi(unittest.TestCase):
    """TeamsApi unit test stubs"""

    def setUp(self):
        self.api = college_football_risk.api.teams_api.TeamsApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_get_team_history(self):
        """Test case for get_team_history

        Get historical team stats  # noqa: E501
        """
        pass

    def test_get_team_strength(self):
        """Test case for get_team_strength

        Get current team strength  # noqa: E501
        """
        pass

    def test_get_teams(self):
        """Test case for get_teams

        Get list of teams  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
