# coding: utf-8

"""
    College Football Risk API

    Companion API for College Football Risk  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Contact: admin@collegefootballdata.com
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest
import datetime

import college_football_risk
from college_football_risk.models.player import Player  # noqa: E501
from college_football_risk.rest import ApiException

class TestPlayer(unittest.TestCase):
    """Player unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional):
        """Test Player
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # model = college_football_risk.models.player.Player()  # noqa: E501
        if include_optional :
            return Player(
                name = '0', 
                team = college_football_risk.models.player_team.Player_team(
                    name = '0', 
                    colors = college_football_risk.models.player_team_colors.Player_team_colors(
                        primary = '0', 
                        secondary = '0', ), ), 
                ratings = college_football_risk.models.player_ratings.Player_ratings(
                    overall = 56, 
                    total_turns = 56, 
                    game_turns = 56, 
                    mvps = 56, 
                    streak = 56, 
                    awards = 56, ), 
                stats = college_football_risk.models.player_stats.Player_stats(
                    total_turns = 56, 
                    game_turns = 56, 
                    mvps = 56, 
                    streak = 56, 
                    awards = 56, ), 
                turns = [
                    college_football_risk.models.player_turns.Player_turns(
                        season = 56, 
                        day = 56, 
                        stars = 56, 
                        mvp = True, 
                        territory = '0', 
                        team = '0', )
                    ]
            )
        else :
            return Player(
        )

    def testPlayer(self):
        """Test Player"""
        inst_req_only = self.make_instance(include_optional=False)
        inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == '__main__':
    unittest.main()
