# coding: utf-8

"""
    College Football Risk API

    Companion API for College Football Risk  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Contact: admin@collegefootballdata.com
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest

import college_football_risk
from college_football_risk.api.stats_api import StatsApi  # noqa: E501
from college_football_risk.rest import ApiException


class TestStatsApi(unittest.TestCase):
    """StatsApi unit test stubs"""

    def setUp(self):
        self.api = college_football_risk.api.stats_api.StatsApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_get_leaderboard(self):
        """Test case for get_leaderboard

        Game leaderboard  # noqa: E501
        """
        pass

    def test_get_turns(self):
        """Test case for get_turns

        Get turns list  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
