# coding: utf-8

"""
    College Football Risk API

    Companion API for College Football Risk  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Contact: admin@collegefootballdata.com
    Generated by: https://openapi-generator.tech
"""


import pprint
import re  # noqa: F401

import six

from college_football_risk.configuration import Configuration


class Territory(object):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    """
    Attributes:
      openapi_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    openapi_types = {
        'id': 'int',
        'name': 'str',
        'short_name': 'str',
        'owner': 'str',
        'neighbors': 'list[TerritoryNeighbors]'
    }

    attribute_map = {
        'id': 'id',
        'name': 'name',
        'short_name': 'shortName',
        'owner': 'owner',
        'neighbors': 'neighbors'
    }

    def __init__(self, id=None, name=None, short_name=None, owner=None, neighbors=None, local_vars_configuration=None):  # noqa: E501
        """Territory - a model defined in OpenAPI"""  # noqa: E501
        if local_vars_configuration is None:
            local_vars_configuration = Configuration()
        self.local_vars_configuration = local_vars_configuration

        self._id = None
        self._name = None
        self._short_name = None
        self._owner = None
        self._neighbors = None
        self.discriminator = None

        if id is not None:
            self.id = id
        if name is not None:
            self.name = name
        if short_name is not None:
            self.short_name = short_name
        if owner is not None:
            self.owner = owner
        if neighbors is not None:
            self.neighbors = neighbors

    @property
    def id(self):
        """Gets the id of this Territory.  # noqa: E501


        :return: The id of this Territory.  # noqa: E501
        :rtype: int
        """
        return self._id

    @id.setter
    def id(self, id):
        """Sets the id of this Territory.


        :param id: The id of this Territory.  # noqa: E501
        :type: int
        """

        self._id = id

    @property
    def name(self):
        """Gets the name of this Territory.  # noqa: E501


        :return: The name of this Territory.  # noqa: E501
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name):
        """Sets the name of this Territory.


        :param name: The name of this Territory.  # noqa: E501
        :type: str
        """

        self._name = name

    @property
    def short_name(self):
        """Gets the short_name of this Territory.  # noqa: E501


        :return: The short_name of this Territory.  # noqa: E501
        :rtype: str
        """
        return self._short_name

    @short_name.setter
    def short_name(self, short_name):
        """Sets the short_name of this Territory.


        :param short_name: The short_name of this Territory.  # noqa: E501
        :type: str
        """

        self._short_name = short_name

    @property
    def owner(self):
        """Gets the owner of this Territory.  # noqa: E501


        :return: The owner of this Territory.  # noqa: E501
        :rtype: str
        """
        return self._owner

    @owner.setter
    def owner(self, owner):
        """Sets the owner of this Territory.


        :param owner: The owner of this Territory.  # noqa: E501
        :type: str
        """

        self._owner = owner

    @property
    def neighbors(self):
        """Gets the neighbors of this Territory.  # noqa: E501


        :return: The neighbors of this Territory.  # noqa: E501
        :rtype: list[TerritoryNeighbors]
        """
        return self._neighbors

    @neighbors.setter
    def neighbors(self, neighbors):
        """Sets the neighbors of this Territory.


        :param neighbors: The neighbors of this Territory.  # noqa: E501
        :type: list[TerritoryNeighbors]
        """

        self._neighbors = neighbors

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.openapi_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, Territory):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, Territory):
            return True

        return self.to_dict() != other.to_dict()
